5.2. Базовые виджеты для взаимодействия с пользователем
alexgogotov/places pull request #13
Opened 2021-06-04 09:08 UTC by alexgogotov

2021-06-07 19:18 UTC, artem-zaitsev requested changes
Необходимы правки, плсмотрите как устроены другие виджеты во фреймворке

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/res/themes.dart
> +class myAppTheme with ChangeNotifier {
классы именуются в PascalCase

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/screen/filters_screen.dart
> +    'hotel': false,
ключи категорий лучше сделать enum

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/screen/filters_screen.dart
> +    'hotel': false,
избежите ошибок из-за опечаток в будущем

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/res/text_content.dart
> +var textContent = {
зачем так сложно? не совсем понятно зачем

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/screen/filters_screen.dart
> +  var par;
почему не final? Да и название ничего не говорит вообще

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/screen/filters_screen.dart
> +  var par;
параметры виджетов зачастую final так как сам виджет иммутабелен

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/screen/filters_screen.dart
> +  var par;
имею ввиду стейтлесс виджетов

2021-06-07 19:18 UTC, artem-zaitsev commented on lib/ui/screen/filters_screen.dart
> +  var par;
А вот использовать чужой сткйт таким образом - это прям совсем антипаттерн. Тут должен быть колбек, а который обрабатывается извне.

 т.е void Function()  onPressed;

а обрабытваться будет вместо this, примерно так:
```
CategoryButton(
      FilterCategory.hotel,
      onPressed: () { 
          setState(){//тут обработка} 
      },
)
```

Посмотрите как устроены кнопки во Flutter.

2021-06-08 10:50 UTC, alexgogotov commented
Внес изменения по всем замечаниям.

2021-06-12 11:47 UTC, dkrutskikh approved these changes

2021-06-15 08:03 UTC, merged